#include "bandit.h"
#include "polctrl.h"
#include "fixedpoint.h"

/*
 * Contextual bandit (tabular UCB1) implementation.
 *
 * LUT approach:
 *   sqrt(ln(N+1)) is precomputed in SQRT_LN_LUT for N = 0..127 (saturating).
 *   sqrt(n+1) is computed via integer square root (isqrt).
 *
 * Q-value update:
 *   Uses EMA with step size alpha = FP_ONE / min(count+1, 255).
 *   For count > 254, alpha is effectively 0 (Q has converged).
 *   This avoids precision loss from dividing by large counts in Q8.8.
 */

/* === LUT for sqrt(ln(i+1)) in Q8.8, generated by scripts/generate_lut.py === */
static const uint16_t SQRT_LN_LUT[BANDIT_LUT_SIZE] = {
       0,   213,   268,   301,   325,   343,   357,   369,
     379,   388,   396,   404,   410,   416,   421,   426,
     431,   435,   439,   443,   447,   450,   453,   456,
     459,   462,   465,   467,   470,   472,   474,   477,
     479,   481,   483,   485,   486,   488,   490,   492,
     493,   495,   496,   498,   499,   501,   502,   504,
     505,   506,   508,   509,   510,   511,   512,   514,
     515,   516,   517,   518,   519,   520,   521,   522,
     523,   524,   525,   526,   527,   528,   529,   529,
     530,   531,   532,   533,   534,   534,   535,   536,
     537,   537,   538,   539,   540,   540,   541,   542,
     542,   543,   544,   544,   545,   546,   546,   547,
     548,   548,   549,   549,   550,   551,   551,   552,
     552,   553,   553,   554,   554,   555,   556,   556,
     557,   557,   558,   558,   559,   559,   560,   560,
     561,   561,   562,   562,   563,   563,   563,   564
};

/* === ARM_PROFILES: (a_gain, c_gain) in Q8.8 for each arm === */
const SpsaGainProfile ARM_PROFILES[NUM_ARMS] = {
    { ARM0_A_Q88, ARM0_C_Q88 },  /* Arm 0: conservative */
    { ARM1_A_Q88, ARM1_C_Q88 },  /* Arm 1: cautious explore */
    { ARM2_A_Q88, ARM2_C_Q88 },  /* Arm 2: aggressive exploit */
    { ARM3_A_Q88, ARM3_C_Q88 },  /* Arm 3: aggressive explore */
};

/* === Integer square root (no FPU needed) === */
static uint32_t isqrt(uint32_t n)
{
    uint32_t result = 0;
    uint32_t bit = 1u << 30;  /* Highest power of 4 <= UINT32_MAX */

    /* Scale bit down to largest power of 4 <= n */
    while (bit > n) {
        bit >>= 2;
    }

    while (bit != 0) {
        if (n >= result + bit) {
            n -= result + bit;
            result = (result >> 1) + bit;
        } else {
            result >>= 1;
        }
        bit >>= 2;
    }
    return result;
}

BanditState bandit_init(void)
{
    BanditState s;
    uint8_t b, a;
    for (b = 0; b < NUM_CONTEXT_BUCKETS; b++) {
        for (a = 0; a < NUM_ARMS; a++) {
            s.q_value[b][a] = 0;
            s.count[b][a] = 0;
        }
    }
    s.total_count = 0;
    return s;
}

uint8_t discretize_context(fp_t drift_estimate, fp_t noise_sigma_estimate)
{
    /*
     * Context = drift_level * 2 + noise_level
     *   drift_level: 0 (low, < DRIFT_LOW_THRESH), 1 (mid), 2 (high, > DRIFT_HIGH_THRESH)
     *   noise_level: 0 (low, < NOISE_HIGH_THRESH), 1 (high)
     */
    uint8_t drift_level;
    uint8_t noise_level;

    if (drift_estimate < DRIFT_LOW_THRESH_Q88) {
        drift_level = 0;
    } else if (drift_estimate > DRIFT_HIGH_THRESH_Q88) {
        drift_level = 2;
    } else {
        drift_level = 1;
    }

    if (noise_sigma_estimate > NOISE_HIGH_THRESH_Q88) {
        noise_level = 1;
    } else {
        noise_level = 0;
    }

    return (uint8_t)(drift_level * 2 + noise_level);
}

uint8_t bandit_select_arm(BanditState s, uint8_t context_bucket)
{
    /*
     * UCB1: arm = argmax_a( Q[a] + C * sqrt(ln(N+1) / (n[a]+1)) )
     *
     * Decomposed:
     *   sqrt_ln_N = LUT[min(N, 127)]   (Q8.8)
     *   sqrt_n = isqrt(n[a] + 1)        (plain integer)
     *   bonus = C * sqrt_ln_N / sqrt_n  (Q8.8)
     *
     * In fixed-point:
     *   temp = fp_mul(C, sqrt_ln_N)     -> Q8.8
     *   sqrt_n_q88 = sqrt_n << FP_SHIFT -> Q8.8
     *   bonus = fp_div(temp, sqrt_n_q88) -> Q8.8
     */
    uint8_t best_arm = 0;
    fp_t best_score = FP_MIN;
    uint8_t a;

    /* Index into LUT (saturating at LUT_SIZE-1) */
    uint32_t lut_idx = s.total_count;
    if (lut_idx >= BANDIT_LUT_SIZE) {
        lut_idx = BANDIT_LUT_SIZE - 1;
    }
    fp_t sqrt_ln_N = (fp_t)SQRT_LN_LUT[lut_idx];

    for (a = 0; a < NUM_ARMS; a++) {
        fp_t score;
        fp_t bonus;
        fp_t temp;
        uint32_t sqrt_n;
        fp_t sqrt_n_q88;

        /* If arm never tried, always select it first (force exploration) */
        if (s.count[context_bucket][a] == 0) {
            return a;
        }

        /* Compute UCB1 bonus */
        temp = fp_mul(C_EXPLORE_Q88, sqrt_ln_N);
        sqrt_n = isqrt(s.count[context_bucket][a] + 1);
        sqrt_n_q88 = (fp_t)(sqrt_n << FP_SHIFT);
        bonus = fp_div(temp, sqrt_n_q88);

        score = s.q_value[context_bucket][a] + bonus;

        if (score > best_score) {
            best_score = score;
            best_arm = a;
        }
    }

    return best_arm;
}

BanditState bandit_update(BanditState s, uint8_t context_bucket, uint8_t arm,
                          fp_t reward)
{
    fp_t diff;
    fp_t alpha;
    uint32_t effective_count;

    s.count[context_bucket][arm]++;
    s.total_count++;

    /* EMA update with step size 1/min(count, 255) */
    effective_count = s.count[context_bucket][arm];
    if (effective_count > 255) {
        effective_count = 255;
    }
    /* alpha = FP_ONE / effective_count (integer division in Q8.8) */
    alpha = (fp_t)(FP_ONE / (int32_t)effective_count);
    if (alpha == 0) {
        alpha = 1;  /* Smallest nonzero Q8.8 step */
    }

    diff = reward - s.q_value[context_bucket][arm];
    s.q_value[context_bucket][arm] += fp_mul(alpha, diff);

    return s;
}
