"""
generate_lut.py — Generate lookup table for UCB1 bonus computation.

Generates sqrt(ln(i+1)) in Q8.8 for i = 0..127.
This LUT is embedded in c/src/bandit.c as a static const array.

The UCB1 bonus is: C * sqrt(ln(N+1) / (n+1))
We split it as: C * sqrt(ln(N+1)) / sqrt(n+1)
  - sqrt(ln(N+1)) comes from this LUT (indexed by min(N, 127))
  - sqrt(n+1) comes from integer square root (isqrt)
"""

import math

LUT_SIZE = 128

def main():
    print("/* LUT for sqrt(ln(i+1)) in Q8.8, i = 0..127 */")
    print("/* Generated by scripts/generate_lut.py — do not edit manually. */")
    print(f"/* LUT_SIZE = {LUT_SIZE} */")
    print(f"static const uint16_t SQRT_LN_LUT[{LUT_SIZE}] = {{")

    for i in range(LUT_SIZE):
        if i == 0:
            val = 0.0  # sqrt(ln(1)) = sqrt(0) = 0
        else:
            val = math.sqrt(math.log(i + 1))
        q88 = round(val * 256)
        if q88 > 32767:
            q88 = 32767
        if i % 8 == 0:
            print("    ", end="")
        print(f"{q88:5d}", end="")
        if i < LUT_SIZE - 1:
            print(",", end="")
        if (i + 1) % 8 == 0:
            print()
        else:
            print(" ", end="")

    print("};")
    print()
    print(f"/* Verification values:")
    for i in [0, 1, 9, 49, 99, 127]:
        if i == 0:
            val = 0.0
        else:
            val = math.sqrt(math.log(i + 1))
        q88 = round(val * 256)
        print(f"   i={i:3d}: sqrt(ln({i+1})) = {val:.4f} -> Q8.8 = {q88}")
    print("*/")


if __name__ == "__main__":
    main()
